# Generated by Django 3.0.5 on 2021-12-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForumApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='update',
            field=models.DateTimeField(auto_now=True, verbose_name='last comment'),
        ),
    ]
