# Generated by Django 3.0.5 on 2022-01-09 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ForumApp', '0004_auto_20220109_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='main_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_replies', to='ForumApp.Comment'),
        ),
    ]
