# Generated by Django 3.0.5 on 2022-01-15 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForumApp', '0005_comment_main_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='update',
            field=models.DateTimeField(auto_now_add=True, verbose_name='last comment'),
        ),
    ]
