# Generated by Django 3.0.5 on 2022-01-18 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ForumApp', '0008_auto_20220118_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='subscribers',
        ),
    ]
