# Generated by Django 3.0.5 on 2022-01-18 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ForumApp', '0011_auto_20220118_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='subscribers',
        ),
    ]
